import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rickyyy
 */
public class CekCuaca extends javax.swing.JFrame {
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane scrollPane;
    /**
     * Creates new form CekCuaca
     */
    public CekCuaca() {
        initComponents();
        dataTable = new JTable(new DefaultTableModel(new Object[]{"Kota", "Kondisi Cuaca"}, 0));
        scrollPane = new JScrollPane(dataTable);

                // Tambahkan ItemListener ke JComboBox untuk mendeteksi perubahan pilihan
        cmbPilihKota.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String selectedCity = (String) cmbPilihKota.getSelectedItem();
                    City.setText(selectedCity);  // Set kota text field dengan pilihan dari combo box
                    System.out.println("Kota favorit dipilih: " + selectedCity);
                }
            }
        });
    }
    private void updateWeatherIcon(String condition) {
    String iconPath = "/images/default.png";
    
    switch (condition.toLowerCase()) {
        case "clear":
        case "sunny":
            iconPath = "/images/sunny.png";
            break;
        case "rain":
        case "rainy":
        case "patchy rain nearby":
        case "showers":
        case "patchy light rain":
        case "moderate rain at times":
            iconPath = "/images/rainy.png";
            break;
        case "cloudy":
        case "overcast":
        case "partly cloudy":
            iconPath = "/images/cloudy.png";
            break;
        case "thunderstorm":
        case "patchy light rain with thunder":
        case "light rain shower":
        case "storm":
            iconPath = "/images/thunderstorm.png";
            break;
        default:
            iconPath = "/images/default.png";
            break;
    }
    
    gambar.setIcon(new ImageIcon(getClass().getResource(iconPath)));
}
    private boolean kotaAdaDiComboBox(String kota) {
    for (int i = 0; i < cmbPilihKota.getItemCount(); i++) {
        if (cmbPilihKota.getItemAt(i).equalsIgnoreCase(kota)) {
            return true;
        }
    }
    return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        City = new javax.swing.JTextField();
        lblhasilCuaca = new javax.swing.JLabel();
        btncekCuaca = new javax.swing.JButton();
        btnsaveFav = new javax.swing.JButton();
        btnsaveData = new javax.swing.JButton();
        btnuploadData = new javax.swing.JButton();
        gambar = new javax.swing.JLabel();
        cmbPilihKota = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbluploadData = new javax.swing.JTable();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        lblhasilCuaca.setText("Keadaan Cuaca");

        btncekCuaca.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btncekCuaca.setText("Cek Cuaca");
        btncekCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekCuacaActionPerformed(evt);
            }
        });

        btnsaveFav.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsaveFav.setText("Simpan Favorit");
        btnsaveFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveFavActionPerformed(evt);
            }
        });

        btnsaveData.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsaveData.setText("Simpan Data");
        btnsaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveDataActionPerformed(evt);
            }
        });

        btnuploadData.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnuploadData.setText("Upload Data");
        btnuploadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadDataActionPerformed(evt);
            }
        });

        cmbPilihKota.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbPilihKota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gambut", "Banjarmasin", "Banjarbaru", "Martapura", "Barabai", "Kandangan" }));

        tbluploadData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kota ", "Kondisi Cuaca"
            }
        ));
        jScrollPane1.setViewportView(tbluploadData);

        btnKeluar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblhasilCuaca)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(356, 356, 356)
                            .addComponent(btnuploadData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(54, 54, 54))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(262, 262, 262)
                            .addComponent(btnKeluar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncekCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPilihKota, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsaveFav))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncekCuaca)
                    .addComponent(cmbPilihKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsaveFav))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhasilCuaca)
                    .addComponent(btnsaveData))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnuploadData)))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncekCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekCuacaActionPerformed
        // Ambil input kota dari JTextField atau dari pilihan JComboBox
        String city = City.getText();
        
        // Panggil method getWeather dan ambil data cuaca
        String weatherCondition = CuacaClass.getWeather(city);
        
        // Tampilkan kondisi cuaca di JLabel
        lblhasilCuaca.setText("Kondisi Cuaca : " + weatherCondition);
        
        // Update gambar berdasarkan kondisi cuaca
        updateWeatherIcon(weatherCondition);
    }//GEN-LAST:event_btncekCuacaActionPerformed

    private void btnsaveFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveFavActionPerformed
        String kotaFavorit = City.getText();
        if (!kotaFavorit.isEmpty() && !kotaAdaDiComboBox(kotaFavorit)) {
            cmbPilihKota.addItem(kotaFavorit);
            System.out.println("Kota " + kotaFavorit + " ditambahkan ke favorit.");
        } else {
            System.out.println("Kota sudah ada di favorit atau input kosong.");
    }                                   
    }//GEN-LAST:event_btnsaveFavActionPerformed

    private void btnsaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveDataActionPerformed
        try (PrintWriter writer = new PrintWriter(new File("dataCuaca.csv"))) {
            writer.println("Kota, Kondisi Cuaca");
            String city = City.getText();
            String weatherCondition = lblhasilCuaca.getText().replace("Kondisi Cuaca : ", "");
            writer.println(city + ", " + weatherCondition);
            JOptionPane.showMessageDialog(null, "Data cuaca berhasil disimpan ke CSV");
        } catch (Exception ex) {
            ex.printStackTrace();
    }                             
    }//GEN-LAST:event_btnsaveDataActionPerformed

    private void btnuploadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadDataActionPerformed
    DefaultTableModel model = (DefaultTableModel) tbluploadData.getModel();

    try (BufferedReader br = new BufferedReader(new FileReader("dataCuaca.csv"))) {
        String line;
        while ((line = br.readLine()) != null) {
            if (line.startsWith("Kota")) continue; // Skip header row

            String[] data = line.split(",");
            model.addRow(data); // Add data to the table without clearing it
        }
        JOptionPane.showMessageDialog(null, "Data berhasil dimuat dari CSV");
    } catch (Exception ex) {
        ex.printStackTrace();
    }                           
    }//GEN-LAST:event_btnuploadDataActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekCuaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField City;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btncekCuaca;
    private javax.swing.JButton btnsaveData;
    private javax.swing.JButton btnsaveFav;
    private javax.swing.JButton btnuploadData;
    private javax.swing.JComboBox<String> cmbPilihKota;
    private javax.swing.JLabel gambar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblhasilCuaca;
    private javax.swing.JTable tbluploadData;
    // End of variables declaration//GEN-END:variables
}
